version: '3.8'

services:
  rust-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/myapp
      - cargo_cache:/usr/local/cargo/registry
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  cargo_cache:
  redis_data:
  postgres_data:
